apiVersion: apps/v1
kind: Deployment
metadata:
  name: argus-agent
spec:
  template:
    spec:
      containers:
        - name: agent
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 2Gi
