[package]
name = "supervisor"
version.workspace = true
edition.workspace = true

[[bin]]
name = "supervisor"
path = "src/main.rs"

[dependencies]
sandbox = { path = "../sandbox" }
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
serde_json.workspace = true
nix.workspace = true
libc = "0.2"
serde_yaml = "0.9"

[dev-dependencies]
tempfile = "3"
